package com.shefit

import android.os.Build
import com.facebook.react.bridge.Promise
import com.facebook.react.bridge.ReactApplicationContext

// NativeGymGirlDeviceInfoSpec is generated by Codegen — it's the C++ interface bridge
class DeviceInfoModule(reactContext: ReactApplicationContext) :
    NativeGymGirlDeviceInfoSpec(reactContext) {

    override fun getName() = "GymGirlDeviceInfo"

    // No @ReactMethod needed — Codegen interface already declares these
    override fun getDeviceModel(promise: Promise) {
        promise.resolve("${Build.MANUFACTURER} ${Build.MODEL}")
    }

    override fun getSystemVersion(promise: Promise) {
        promise.resolve(Build.VERSION.RELEASE)
    }

    override fun isEmulator(promise: Promise) {
        val result = (Build.FINGERPRINT.startsWith("generic")
            || Build.FINGERPRINT.startsWith("unknown")
            || Build.MODEL.contains("google_sdk")
            || Build.MODEL.contains("Emulator")
            || Build.MODEL.contains("Android SDK"))
        promise.resolve(result)
    }
}
